In [4]:
# Write note data both as table with note value info
# and as list with unique onset times

import numpy as np
import pandas as pd

In [5]:
NOTES = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']
OCTAVES = list(range(11))
NOTES_IN_OCTAVE = len(NOTES)

In [6]:
def number_to_note(number: int) -> tuple:
    octave = number // NOTES_IN_OCTAVE
    assert octave in OCTAVES, errors['notes']
    assert 0 <= number <= 127, errors['notes']
    note = NOTES[number % NOTES_IN_OCTAVE]

    return note, octave

In [60]:
# OBS! This is not for nmat, really

fname = "HahnGiguePartita2"
path = "datasets/sturmbach/sturmbach_labels/{}.txt".format(fname)
out_path = "datasets/sturmbach/sturmbach_labels/{}.midi.csv".format(fname)

In [62]:
col_names = ["onset", "offset", "pitch"]
notes = pd.read_csv(path)
notes

        onset     offset  pitch
0    0.123000   0.239000     69
1    0.437000   0.750000     62
2    0.750000   0.947000     65
3    0.982000   1.261000     69
4    1.261000   1.574000     74
..        ...        ...    ...
81  13.509000  13.649000     62
82  13.660000  13.881000     57
83  13.962000  14.218000     74
84  14.229000  14.499237     73
85  14.559212  15.039009     62

[86 rows x 3 columns]

In [63]:
notes["note"] = [number_to_note(pitch)[0] for pitch in notes["pitch"]]
notes["octave"] = [number_to_note(pitch)[1] for pitch in notes["pitch"]]
notes

        onset     offset  pitch note  octave
0    0.123000   0.239000     69    A       5
1    0.437000   0.750000     62    D       5
2    0.750000   0.947000     65    F       5
3    0.982000   1.261000     69    A       5
4    1.261000   1.574000     74    D       6
..        ...        ...    ...  ...     ...
81  13.509000  13.649000     62    D       5
82  13.660000  13.881000     57    A       4
83  13.962000  14.218000     74    D       6
84  14.229000  14.499237     73   C#       6
85  14.559212  15.039009     62    D       5

[86 rows x 5 columns]

In [64]:
notes.to_csv(out_path, index=False)

In [18]:
sc_unique_onsets = np.unique(sc_onsets)
df2 = pd.DataFrame({"onset":sc_unique_onsets})
df2.to_csv(path[:-4] + ".onsets", index=False, header=False)